version: 2
registries:
  k9-format:
    type: maven-repository
    url: https://maven.pkg.github.com/navikt/k9-format
    username: x-access-token
    password: ${{secrets.READER_TOKEN}}
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
    registries:
      - k9-format
    groups:
      patterns:
        - "*"
        
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    groups:
      github-actions:
        patterns:
          - "*"
