version: 2
registries:
  k9-format:
    type: maven-repository
    url: https://maven.pkg.github.com/navikt/k9-format
    username: x-access-token
    password: ${{secrets.DEPENDABOT_ACCESS_TOKEN}}
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    registries:
      - k9-format
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
