name-template: $NEXT_PATCH_VERSION
tag-template: $NEXT_PATCH_VERSION
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
commitish: 'master'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '⚠️ Breaking Changes'
    labels:
      - 'breaking'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
  - title: '⬆️ Dependency upgrades'
    labels:
      - 'bump'
      - 'dependencies'
autolabeler:
  - label: 'chore'
    title:
      - '/^chore:/i'
    files:
      - '*.md'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/^fix:/i'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
    title:
      - '/^feature:/i'
    body:
      - '/^[A-Z]{3,8}-[0-9]{1,4}:/'
  - label: 'kontrakt'
    files:
      - '*.java'
  - label: 'pom'
    files:
      - 'pom.xml'
include-labels:
  - 'kontrakt'
template: |
  ## What's Changed
  $CHANGES
