name: Bygg

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '.gitignore'
      - 'LICENCE'
      - 'CODEOWNERS'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build & Deploy
        run: |
             mvn install -e --batch-mode --settings .github/settings.xml --file pom.xml -DtrimStackTrace=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
