name: Pull request bygg

on: 
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '.gitignore'
      - 'LICENCE'
      - 'CODEOWNERS'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'
      - name: Build
        run: mvn verify --settings .github/settings.xml -DtrimStackTrace=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
