name: Maven Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: Test and build
        run: ./mvnw clean verify --batch-mode --file pom.xml -Dsha1=".$(git rev-parse --short HEAD)" -Dchangelist=
      - name: Upload artifacts
        run: ./scripts/maven-deploy.sh
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_PASSWORD: ${{ secrets.GITHUB_ACCESS_TOKEN }}
