name: Maven Deploy

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '.gitignore'
      - 'LICENCE'
      - 'CODEOWNERS'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: Build & Deploy
        run: |
             mvn clean deploy --batch-mode --settings ./.github/settings.xml -Dmaven.wagon.http.pool=false --file pom.xml -Dsha1="-$(git log -1 --pretty='%ad' --date=format:'%Y%m%d%H%M%S')-$(git rev-parse --short HEAD)" -Dchangelist=
             echo "::set-env name=MVN_VERSION::$(mvn help:evaluate --batch-mode --settings ./.github/settings.xml --file .flattened -Dexpression=project.version -q -DforceStdout)"
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_PASSWORD: ${{ secrets.GITHUB_ACCESS_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.MVN_VERSION }}
          release_name: Release ${{ env.MVN_VERSION }}
          draft: false
          prerelease: false
