name: Publish kontrakt
on:
  release:
    types: [published]

jobs:
  build:
    name: Bygg pull-request
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4.1.6
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Verify
        shell: bash
        run: |
           mvn verify -e -B --file pom.xml --settings .github/settings.xml -DtrimStackTrace=false -Dtoken=${GITHUB_TOKEN}
        env:
          GITHUB_TOKEN: ${{ secrets.READER_TOKEN }}
          NEW_VERSION: ${{ github.event.release.tag_name }}
      - name: Publish artifacts
        shell: bash
        run: |
           mvn deploy -e -B --file pom.xml --settings .github/settings.xml -DtrimStackTrace=false -Dchangelist= -Dsha1= -Drevision=$NEW_VERSION -Dfile.encoding=UTF-8 -Dtoken=${GITHUB_TOKEN}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEW_VERSION: ${{ github.event.release.tag_name }}

